version: '3.9'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - "db:database"
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: /home/gradle/buildWorkspace/app/build/distributions/app/bin/app

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nttdata
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local